#!/usr/bin/env python3
"""
wav2adpcm.py -- 打包 16kHz/mono/s16le WAV → voice.bin(IMA-ADPCM)+ 生成 voice_ids.h。
打包格式 = voice_adpcm.c 解析格式(鎖死,指南 §19.2)。

voice.bin(全小端):
  檔頭:  magic "PKV1"(4B) | u16 count | u16 version=1
  索引表: count × { u32 data_off | u32 adpcm_bytes | u32 pcm_samples }
  資料區: 每 clip = 4B 狀態頭 { s16 initial_predictor | u8 initial_step_index | u8 rsv=0 }
          + IMA-ADPCM nibble 流(低 nibble 在前;奇數樣本尾 nibble 補 0)
編碼:每 clip 狀態獨立重置;首樣本進狀態頭,自第 2 樣本起編 nibble。
V_BEEP:內建生成 880Hz、120ms、-6dBFS 正弦後照常編碼。
"""
import sys, os, struct, wave, math, argparse

STEP_TABLE = [
    7,8,9,10,11,12,13,14,16,17,19,21,23,25,28,31,34,37,41,45,50,55,60,66,73,80,
    88,97,107,118,130,143,157,173,190,209,230,253,279,307,337,371,408,449,494,
    544,598,658,724,796,876,963,1060,1166,1282,1411,1552,1707,1878,2066,2272,
    2499,2749,3024,3327,3660,4026,4428,4871,5358,5894,6484,7132,7845,8630,9493,
    10442,11487,12635,13899,15289,16818,18500,20350,22385,24623,27086,29794,32767]
INDEX_TABLE = [-1,-1,-1,-1,2,4,6,8,-1,-1,-1,-1,2,4,6,8]

def clamp(v, lo, hi):
    return lo if v < lo else hi if v > hi else v

def ima_encode(samples):
    """回傳 (initial_predictor, initial_step_index, nibble_bytes)。首樣本進狀態頭。"""
    if not samples:
        return 0, 0, b""
    predictor = int(samples[0])
    step_index = 0
    nibbles = []
    for i in range(1, len(samples)):
        step = STEP_TABLE[step_index]
        diff = int(samples[i]) - predictor
        sign = 8 if diff < 0 else 0
        if diff < 0:
            diff = -diff
        delta = 0
        vpdiff = step >> 3
        if diff >= step:
            delta = 4; diff -= step; vpdiff += step
        step >>= 1
        if diff >= step:
            delta |= 2; diff -= step; vpdiff += step
        step >>= 1
        if diff >= step:
            delta |= 1; vpdiff += step
        if sign:
            predictor -= vpdiff
        else:
            predictor += vpdiff
        predictor = clamp(predictor, -32768, 32767)
        delta |= sign
        step_index = clamp(step_index + INDEX_TABLE[delta], 0, 88)
        nibbles.append(delta & 0x0F)
    # 打包 nibble:低 nibble 在前
    out = bytearray()
    for k in range(0, len(nibbles), 2):
        lo = nibbles[k]
        hi = nibbles[k + 1] if k + 1 < len(nibbles) else 0
        out.append(lo | (hi << 4))
    return int(samples[0]), 0, bytes(out)

def read_wav(path):
    with wave.open(path, 'rb') as w:
        if w.getnchannels() != 1 or w.getsampwidth() != 2 or w.getframerate() != 16000:
            raise SystemExit("ERROR: %s must be 16000Hz mono s16le (got %dch %dbit %dHz)" %
                             (path, w.getnchannels(), w.getsampwidth() * 8, w.getframerate()))
        raw = w.readframes(w.getnframes())
    n = len(raw) // 2
    return list(struct.unpack("<%dh" % n, raw))

def gen_beep():
    sr, freq, ms = 16000, 880.0, 120
    n = sr * ms // 1000
    amp = int(32767 * 0.5)  # -6 dBFS
    return [int(amp * math.sin(2 * math.pi * freq * i / sr)) for i in range(n)]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("list_tsv")
    ap.add_argument("wav_dir")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--header", required=True)
    args = ap.parse_args()

    ids, texts = [], []
    with open(args.list_tsv, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            parts = line.split("\t")
            vid = parts[0].strip()
            txt = parts[1].strip() if len(parts) > 1 else ""
            ids.append(vid); texts.append(txt)

    clips = []  # (predictor, step_index, nibble_bytes, pcm_samples)
    for vid in ids:
        if vid == "V_BEEP":
            samples = gen_beep()
        else:
            wav = os.path.join(args.wav_dir, vid + ".wav")
            if not os.path.exists(wav):
                raise SystemExit("ERROR: missing wav for %s (%s)" % (vid, wav))
            samples = read_wav(wav)
        p, si, nib = ima_encode(samples)
        clips.append((p, si, nib, len(samples)))

    count = len(clips)
    header_bytes = 8
    index_bytes = count * 12
    data_off = header_bytes + index_bytes
    index = bytearray()
    data = bytearray()
    for (p, si, nib, nsamp) in clips:
        clip_off = data_off + len(data)
        clip = struct.pack("<hBB", p, si, 0) + nib
        adpcm_bytes = len(clip)
        index += struct.pack("<III", clip_off, adpcm_bytes, nsamp)
        data += clip

    with open(args.output, "wb") as f:
        f.write(b"PKV1")
        f.write(struct.pack("<HH", count, 1))
        f.write(index)
        f.write(data)

    # voice_ids.h
    with open(args.header, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by wav2adpcm.py - DO NOT EDIT\n")
        f.write("typedef enum {\n")
        for i, vid in enumerate(ids):
            f.write("    %s = %d,\n" % (vid, i))
        f.write("    VOICE_COUNT\n")
        f.write("} voice_id_t;\n")
        f.write("#define VOICE_BIN_MAGIC 0x31564B50u   // \"PKV1\"\n")

    # 自檢:枚舉連續性(§19.2)
    idmap = {v: i for i, v in enumerate(ids)}
    if "V_N0" in idmap and "V_N20" in idmap:
        assert idmap["V_N0"] + 20 == idmap["V_N20"], "V_N0..V_N20 must be contiguous"
    if "V_N30" in idmap and "V_N90" in idmap:
        assert idmap["V_N30"] + 6 == idmap["V_N90"], "V_N30..V_N90 must be contiguous"

    total = os.path.getsize(args.output)
    print("voice.bin: %d clips, %d bytes (index %d, data %d)" %
          (count, total, index_bytes, len(data)))

if __name__ == "__main__":
    main()
